USE QLSHOPDH;
CREATE TABLE Users(
 ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 NAME VARCHAR(125) ,
 PASSWORD VARCHAR(255)
);
ALTER TABLE Users AUTO_INCREMENT = 1;

CREATE TABLE Products(
 IDP INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 TYPEP VARCHAR(100),
 NAMEP VARCHAR(150),
 PRICE INT ,
 AMOUNT INT
);
ALTER TABLE Products AUTO_INCREMENT = 1;